name: 'linkedin_ads'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  linkedin_ads:
    vars:
      etl:                                   #stitch or fivetran
