version: 2

models:
  - name: linkedin_ads_accounts
    columns:
        - name: account_id
          tests:
              - unique
              - not_null
              
  - name: linkedin_ads_campaign_groups
    columns:
        - name: campaign_group_id
          tests:
              - unique
              - not_null
              
  - name: linkedin_ads_creatives
    columns:
        - name: creative_id
          tests:
              - unique
              - not_null
              
  - name: linkedin_ads_campaigns
    columns:
        - name: campaign_id
          tests:
              - unique
              - not_null
              
  - name: linkedin_ads_creative_performance
    columns:
        - name: creative_performance_report_id
          tests:
              - unique
              - not_null